### ISSUE TITLE
Change namespace?

### ISSUE THREAD

**Issue by rlktradewright** [tradewright/tabcontrol-extra#1]
The current version of the TabControlExtra control uses the System.Windows.Forms namespace. The original justification for doing so is that it makes it easy to substitute TabControlExtra in a program that already uses the Microsoft TabControl.

I'm uncomfortable using this namespace, as it really seems a bit of a cheek to me, although there aren't any technical problems with it. I feel that Microsoft 'owns' System.Windows.Forms, and we shouldn't really be using it for our own purposes.

So I propose a namespace change to something that fits in with the TradeWright namespace scheme. This would be something like:

`TradeWright.UI.Forms`

I realise this is a breaking change and would require changing some existing references or adding new `using` or `Imports` statements, but these changes are trivial (and I suspect few people are using TabControlExtra anyway).

So any reactions to this proposed change please?

**Comment by mikyjazz** [comment]
Hi Richard, change the namespace ...
Undoubtedly Windows.Forms was more comfortable but change the code, as you say, it would still be trivial :)

**Comment by rlktradewright** [comment]
Namespace was changed in commit SHA: 9d8917c7cc9da909cb6315688e02a3ff61a90750
