### ISSUE TITLE
Issue with TabClosing event

### ISSUE THREAD

**Issue by gmattis** [tradewright/tabcontrol-extra#2]
I'm currently using your custom control for a private software (and it is perfect by the way), but I ran into an issue dealing with the TabClosing event.
This event is currently raised after the tab is closed, instead of being raised before the tab is closed. It seems like moving the `if (this.TabClosing != null)` statement at the top of the OnTabClosing method (in TabControlExtra.cs) solves the issue. May you make a commit solving the problem? Thank you for your great work!

**Comment by rlktradewright** [comment]
Ok, I'll look into it. Not immediately though...

**Comment by rlktradewright** [comment]
You're right, there's definitely a fault there, well spotted! I'll try to commit a fix over the weekend.

**Comment by gmattis** [comment]
Thank you!
